version: '3.6'
services:
  mssql:
    container_name: mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'StrongPassword!'
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - mssql
    ports:
      - "1433:1433/tcp"
    restart: always
    user: root
    volumes:
      - mssql-backup:/var/opt/mssql/backup
      - mssql-data:/var/opt/mssql/data
networks:
  mssql:
    name: mssql
volumes:
  mssql-backup:
    name: mssql-backup
  mssql-data:
    name: mssql-data
