version: '3.6'
services:
  mssql:
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'StrongPassword!'
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - mssql
    ports:
      - "1433:1433/tcp"
    restart: always
    user: root
    volumes:
      - /mnt/docker/mssql/data:/var/opt/mssql/data
      - /mnt/docker/mssql/backup:/var/opt/mssql/backup

networks:
  mssql: